#!/bin/bash
EXTRA_ARGS=""
if [ "$MESOS_HOME" != "" ]; then
  EXTRA_ARGS="-Djava.library.path=$MESOS_HOME/lib/java"
fi
export SPARK_HOME=$(cd "$(dirname $0)/.."; pwd)
echo $SPARK_HOME
java -Xmx2G -XX:MaxPermSize=2G $EXTRA_ARGS -jar $SPARK_HOME/sbt/sbt-launch-*.jar "$@"

